[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "aiogram-dynamodb-storage"
version = "0.1.0"
dependencies = [
    "aiogram>=3.0.0",
    "aioboto3>=10.0.0"
]

[tool.hatch.build.targets.wheel]
only-include = ["aiogram"]

